In [1]:
!pip install stable-baselines3[extra]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.0/188.0 kB 7.6 MB/s eta 0:00:00


In [28]:
import os
import gymnasium as gym # Changed from gym to gymnasium
from stable_baselines3 import PPO #(model)
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

In [3]:
#loading the environments
env=gym.make('CartPole-v1')

/usr/local/lib/python3.12/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.12/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [4]:
#testing the environment (test it 5 times)
tests=5
for i in range(1,tests+1):
  print(i)

1
2
3
4
5


In [5]:
env.reset() #initial values

array([-0.00655068,  0.04629098,  0.02467186,  0.0017961 ], dtype=float32)

In [6]:
env.action_space.sample() #0 or 1

1

In [7]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [9]:
env.step(1) #reward = 1.0 #true or false tells if the episode is done or not. ## For CartPole, action 1 means moving right

(array([-0.00080385,  0.43581155,  0.01904775, -0.56779057], dtype=float32),
 1.0,
 False,
 {})

In [10]:
for i in range (1,tests+1): #tests/episodes
  state=env.reset()
  score=0
  done=False
  while not done:
    env.render()
    action=env.action_space.sample() #selects a random action from the set of valid actions
    n_state,reward,done,info=env.step(action)
    score+=reward
    print('Test:{} Score:{}'.format(i,score))
env.close()


/usr/local/lib/python3.12/dist-packages/gym/core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(
/usr/local/lib/python3.12/dist-packages/pygame/pkgdata.py:25: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import resource_stream, resource_exists
/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_reso

Test:1 Score:1.0
Test:1 Score:2.0
Test:1 Score:3.0
Test:1 Score:4.0
Test:1 Score:5.0
Test:1 Score:6.0
Test:1 Score:7.0
Test:1 Score:8.0
Test:1 Score:9.0
Test:1 Score:10.0


/usr/local/lib/python3.12/dist-packages/gym/core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(


Test:1 Score:11.0
Test:1 Score:12.0
Test:1 Score:13.0
Test:1 Score:14.0
Test:1 Score:15.0
Test:1 Score:16.0
Test:1 Score:17.0
Test:1 Score:18.0
Test:2 Score:1.0
Test:2 Score:2.0
Test:2 Score:3.0
Test:2 Score:4.0
Test:2 Score:5.0
Test:2 Score:6.0
Test:2 Score:7.0
Test:2 Score:8.0
Test:2 Score:9.0
Test:2 Score:10.0
Test:2 Score:11.0
Test:2 Score:12.0
Test:2 Score:13.0
Test:2 Score:14.0
Test:2 Score:15.0
Test:2 Score:16.0
Test:2 Score:17.0
Test:2 Score:18.0
Test:2 Score:19.0
Test:2 Score:20.0
Test:2 Score:21.0
Test:2 Score:22.0
Test:3 Score:1.0
Test:3 Score:2.0
Test:3 Score:3.0
Test:3 Score:4.0
Test:3 Score:5.0
Test:3 Score:6.0
Test:3 Score:7.0
Test:3 Score:8.0
Test:3 Score:9.0
Test:3 Score:10.0
Test:3 Score:11.0
Test:3 Score:12.0
Test:3 Score:13.0
Test:3 Score:14.0
Test:3 Score:15.0
Test:3 Score:16.0
Test:3 Score:17.0
Test:3 Score:18.0
Test:3 Score:19.0
Test:3 Score:20.0
Test:3 Score:21.0
Test:3 Score:22.0
Test:4 Score:1.0
Test:4 Score:2.0
Test:4 Score:3.0
Test:4 Score:4.0
Test:4 Score:5

Observation Space (env.observation_space): Represents the information the agent receives, such as pixel data, joint angles, or sensory data.

Action Space (env.action_space): Represents all possible moves or decisions an agent can make, such as moving left/right, torque values, or menu selections.

**COMMON SPACE TYPES :**

Discrete: A fixed range of non-negative integers (e.g., Discrete(4) for 4 distinct actions: 0, 1, 2, 3).

Box: A n-dimensional continuous space, representing bounded, numerical data (e.g., coordinates, pixel values).
Dict / Tuple: Combinations of multiple space types

In [11]:
env.observation_space.sample()

array([-7.9727376e-01,  1.5339429e+37, -2.9757687e-01,  1.2283815e+38],
      dtype=float32)

For this problem in the observation space we have cart position, cart velocity,pole angle and pole angular velocity.

In [12]:
PPO??

In [16]:
!pip install shimmy

In [30]:
# shimmy is no longer needed when using gymnasium directly

# Corrected: Create a new environment instance using gymnasium.make
env=DummyVecEnv([lambda: gym.make('CartPole-v1')])
model=PPO('MlpPolicy',env)
model.learn(total_timesteps=20000)

In [32]:
PPO_path=os.path.join('Training','Saved Models','PPO_Model_Cartpole')
model.save(PPO_path)

/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/save_util.py:284: UserWarning: Path 'Training/Saved Models' does not exist. Will create it.
  warnings.warn(f"Path '{path.parent}' does not exist. Will create it.")


In [ ]:
#to delete the model give 'del model'

**Testing and Evaluation**

Two core metrics has to be paid attention to than the other metrics available for training a model.


ep_len_mean and ep_rew_mean which tells how long a particular episode would last before getting done and the avg reward the agent accumulated per episode respectively.


In [34]:
evaluate_policy(model,env,n_eval_episodes=18,render=True)

(np.float64(500.0), np.float64(0.0))

In [35]:
env.close()

In [43]:
#testing model
for i in range (1,tests+1):
  obs=env.reset()
  score=0
  done=False
  while not done:
    env.render()
    action,_=model.predict(obs)
    obs,reward,done,info=env.step(action)
    score+=reward
  print(f"Test:{i} Score:{score.item()}")

/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/vec_env/base_vec_env.py:259: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


Test:1 Score:279.0
Test:2 Score:500.0
Test:3 Score:500.0
Test:4 Score:500.0
Test:5 Score:243.0


In [44]:
obs=env.reset()

In [49]:
model.predict(obs)

(array([1]), None)

TRAINING STRATEGIES:

1. Train for a longer time
2. Hyperparameter tuning
3. Try different algorithms


Callbacks are used to either log out of data or save the model at some particular instant. Keras callbacks are functions that automatically run at specific points during model training to monitor, save, or adjust your model.

In [58]:
#callbacks
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold, StopTrainingOnNoModelImprovement, StopTrainingOnMaxEpisodes
stop_callback= StopTrainingOnRewardThreshold(reward_threshold=200)
# Corrected: Pass stop_callback to EvalCallback's callback_on_new_best argument
eval_callback=EvalCallback(env,best_model_save_path='./logs/', eval_freq=1000, n_eval_episodes=10, callback_on_new_best=stop_callback)
#apply callback to training model
model.learn(total_timesteps=20000,callback=[eval_callback])

/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/evaluation.py:70: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Eval num_timesteps=1000, episode_reward=500.00 +/- 0.00
Episode length: 500.00 +/- 0.00
New best mean reward!


In [65]:
#changing policies
from stable_baselines3 import DQN
model=DQN('MlpPolicy',env,verbose=1)
model.learn(total_timesteps=20000,callback=[eval_callback])


Using cpu device
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.929    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 2399     |
|    time_elapsed     | 0        |
|    total_timesteps  | 150      |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.584    |
|    n_updates        | 12       |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.904    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 2094     |
|    time_elapsed     | 0        |
|    total_timesteps  | 203      |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.548    |
|    n_updates        | 25       |
----------------------------------
----------------------------------
| rollout/            |          |
|  

/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/evaluation.py:70: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Streaming output truncated to the last 5000 lines.
|    loss             | 0.00129  |
|    n_updates        | 1386     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 516      |
|    fps              | 1069     |
|    time_elapsed     | 5        |
|    total_timesteps  | 5688     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.00135  |
|    n_updates        | 1396     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 520      |
|    fps              | 1069     |
|    time_elapsed     | 5        |
|    total_timesteps  | 5725     |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.00235  |
|   

In [67]:
DQN_path = os.path.join('Training', 'Saved Models', 'DQN_Model_Cartpole')
model.save(DQN_path)